apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: llmaz
    app.kubernetes.io/part-of: llmaz
  {{- include "chart.labels" . | nindent 4 }}
  {{- if .Values.controllerManager.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
  {{- end }}