---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: openmodels.llmaz.io
spec:
  group: llmaz.io
  names:
    kind: OpenModel
    listKind: OpenModelList
    plural: openmodels
    shortNames:
    - om
    singular: openmodel
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: OpenModel is the Schema for the open models API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ModelSpec defines the desired state of Model
            properties:
              familyName:
                description: |-
                  FamilyName represents the model type, like llama2, which will be auto injected
                  to the labels with the key of `llmaz.io/model-family-name`.
                type: string
              inferenceConfig:
                description: InferenceConfig represents the inference configurations
                  for the model.
                properties:
                  flavors:
                    description: |-
                      Flavors represents the accelerator requirements to serve the model.
                      Flavors are fungible following the priority represented by the slice order.
                      This is used both in Playground and Inference Service.
                    items:
                      description: |-
                        Flavor defines the accelerator requirements for a model and the necessary parameters
                        in autoscaling. Right now, it will be used in two places:
                        - Pod scheduling with node selectors specified.
                        - Cluster autoscaling with essential parameters provided.
                      properties:
                        limits:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          description: |-
                            Limits defines the required accelerators to serve the model for each replica,
                            like <nvidia.com/gpu: 8>. For multi-hosts cases, the limits here indicates
                            the resource requirements for each replica, usually equals to the TP size.
                            Not recommended to set the cpu and memory usage here:
                            - if using playground, you can define the cpu/mem usage at backendConfig.
                            - if using inference service, you can define the cpu/mem at the container resources.
                            However, if you define the same accelerator resources at playground/service as well,
                            the resources will be overwritten by the flavor limit here.
                          type: object
                        name:
                          description: Name represents the flavor name, which will
                            be used in model claim.
                          type: string
                        nodeSelector:
                          additionalProperties:
                            type: string
                          description: |-
                            NodeSelector represents the node candidates for Pod placements, if a node doesn't
                            meet the nodeSelector, it will be filtered out in the resourceFungibility scheduler plugin.
                            If nodeSelector is empty, it means every node is a candidate.
                          type: object
                        params:
                          additionalProperties:
                            type: string
                          description: |-
                            Params stores other useful parameters and will be consumed by cluster-autoscaler / Karpenter
                            for autoscaling or be defined as model parallelism parameters like TP or PP size.
                            E.g. with autoscaling, when scaling up nodes with 8x Nvidia A00, the parameter can be injected
                            with <INSTANCE-TYPE: p4d.24xlarge> for AWS.
                            Preset parameters: TP, PP, INSTANCE-TYPE.
                          type: object
                      required:
                      - name
                      type: object
                    maxItems: 8
                    type: array
                  sharedMemorySize:
                    anyOf:
                    - type: integer
                    - type: string
                    description: |-
                      SharedMemorySize represents the size of /dev/shm required in the runtime of
                      inference workload.
                      This is only used in Playground. Inference Service can configure the shared memory
                      directly in PodSpec.
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                type: object
              source:
                description: |-
                  Source represents the source of the model, there're several ways to load
                  the model such as loading from huggingface, OCI registry, s3, host path and so on.
                properties:
                  modelHub:
                    description: ModelHub represents the model registry for model
                      downloads.
                    properties:
                      allowPatterns:
                        description: AllowPatterns refers to files matched with at
                          least one pattern will be downloaded.
                        items:
                          type: string
                        type: array
                      filename:
                        description: |-
                          Filename refers to a specified model file rather than the whole repo.
                          This is helpful to download a specified GGUF model rather than downloading
                          the whole repo which includes all kinds of quantized models.
                          in the near future.
                          Note: once filename is set, allowPatterns and ignorePatterns should be left unset.
                        type: string
                      ignorePatterns:
                        description: IgnorePatterns refers to files matched with any
                          of the patterns will not be downloaded.
                        items:
                          type: string
                        type: array
                      modelID:
                        description: |-
                          ModelID refers to the model identifier on model hub,
                          such as meta-llama/Meta-Llama-3-8B.
                        type: string
                      name:
                        default: Huggingface
                        description: Name refers to the model registry, such as huggingface.
                        enum:
                        - Huggingface
                        - ModelScope
                        type: string
                      revision:
                        default: main
                        description: Revision refers to a Git revision id which can
                          be a branch name, a tag, or a commit hash.
                        type: string
                    type: object
                  uri:
                    description: |-
                      URI represents a various kinds of model sources following the uri protocol, protocol://<address>, e.g.
                      - oss://<bucket>.<endpoint>/<path-to-your-model>
                      - ollama://llama3.3
                      - host://<path-to-your-model>
                    type: string
                type: object
            required:
            - familyName
            - source
            type: object
          status:
            description: ModelStatus defines the observed state of Model
            properties:
              conditions:
                description: Conditions represents the Inference condition.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
